version: "3.8"
services: 
  api:
    build: ./backend
    container_name: api_container
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
      - ./app/backend/node_modules
  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - '8080:8080'
    volumes:
      - ./frontend:/app
      - ./app/frontend/node_modules
    stdin_open: true
    tty: true